# -----------------------------------------------------------------------------
# ~/.config/brew/Brewfile
# -----------------------------------------------------------------------------

# Instructions:
#   1. Install Homebrew
#   2. `brew tap homebrew/bundle`
#   3. `brew bundle --file=$THIS_FILE`
#   4. `brew bundle --file=~/.local/config/brew/Brewfile` [optional]

tap "homebrew/dupes"
tap "homebrew/versions"

# -----------------------------------------------------------------------------
# essentials
# -----------------------------------------------------------------------------

# for Linuxbrew
brew "gcc" if OS.linux?

# for Homebrew
brew "openssl"
brew "curl", args: ["with-nghttp2"]
brew "git", args: ["with-brewed-curl", "with-brewed-openssl"]

# bash 4
brew "bash", args: ["devel"]
brew "homebrew/versions/bash-completion2"

# tmux
brew "tmux"
brew "reattach-to-user-namespace" if OS.mac?

# other
brew "dtrx", args: ["with-cabextract", "with-lha", "with-unshield"]
brew "vim", args: ["override-system-vi"]
brew "wget", args: ["HEAD", "enable-iri", "with-pcre"]
brew "homebrew/dupes/less", args: ["with-pcre"]
brew "homebrew/dupes/ncurses"

# -----------------------------------------------------------------------------
# GNU utilities
# -----------------------------------------------------------------------------

if OS.mac?
  brew "coreutils", args: ["HEAD"]

  brew "gawk"
  brew "gnu-tar"

  # parallel (moreutils must be installed `--without-parallel`)
  brew "parallel"

  # moreutils (conflicts w/ GNU parallel)
  brew "moreutils", args: ["without-parallel"]

  # find, locate, updatedb, and xargs (do not prepend "g" to the binaries)
  brew "findutils", args: ["default-names"]

  # sed (overwrite built-in)
  brew "gnu-sed", args: ["default-names"]

  # grep (overwrite built-in)
  brew "homebrew/dupes/grep", args: ["with-default-names"]
end

# -----------------------------------------------------------------------------
# internet stuff
# -----------------------------------------------------------------------------

brew "links"

if OS.mac?
  brew "homebrew/dupes/rsync"
  brew "homebrew/dupes/whois"
end

# -----------------------------------------------------------------------------
# development
# -----------------------------------------------------------------------------

if MacOS.version >= "10.6"
  brew "rbenv"
  brew "ruby-build"
  brew "rbenv-bundler"
end

brew "python"
brew "jq"

# -----------------------------------------------------------------------------
# other stuff
# -----------------------------------------------------------------------------

if OS.mac?
  brew "rename"
  brew "tree"
  brew "watch"
end

# images
brew "pngcrush"

# OpenSSH
brew "homebrew/dupes/openssh"
brew "ssh-copy-id"

# text
brew "dos2unix"
brew "multimarkdown"

# misc.
brew "binutils"
brew "ghostscript"
brew "groff"
brew "source-highlight" # for less
brew "homebrew/dupes/srm"
brew "stow"
