source "https://rubygems.org"
ruby "~> 3.1.0"

# -- general -------------------------------------------------------------------

# <github.com/busyloop/lolcat>
gem "lolcat"

# <github.com/rtomayko/ronn>
gem "ronn", "~> 0.7"

# <github.com/TamerShlash/symbolized>
gem "symbolized"

# <github.com/lsegal/yard>
gem "yard", ">= 0.9.20"

# -- for Visual Studio Code ----------------------------------------------------

# <solargraph.org>
gem "solargraph"
# <github.com/sds/slim-lint>
gem "slim_lint"

# -- webdev --------------------------------------------------------------------

# <github.com/middleman/middleman>
gem "middleman"

# <github.com/sass/sass>
gem "sassc"

# <github.com/slim-template/slim>
gem "slim"

# -- for pyjamas.fish ----------------------------------------------------------

# <github.com/bleything/plist>
gem "plist"
# <https://github.com/emancu/toml-rb>
gem "toml-rb"

# -- for Markdown-to-HTML post-processing --------------------------------------

# <github.com/threedaymonk/htmlentities>
gem "htmlentities"

# -- local gems ----------------------------------------------------------------

gem "pyjamas", path: "../../../Developer/ruby/pyjamas"
gem "tiny_dancer", path: "../../../src/z/tiny_dancer"
