# install with `gem install -g ~/.config/ruby/Gemfile`

source "https://rubygems.org"

# -----------------------------------------------------------------------------
# Utilities
# -----------------------------------------------------------------------------

# <github.com/threedaymonk/htmlentities>
gem "htmlentities"

# <github.com/bleything/plist>
gem "plist"

# <github.com/rtomayko/ronn>
gem "ronn", "~> 0.7"

# <github.com/TamerShlash/symbolized>
gem "symbolized"

# <github.com/lsegal/yard>
gem "yard", ">= 0.9.20"

# for Visual Studio Code
gem "solargraph"

# -----------------------------------------------------------------------------
# Misc.
# -----------------------------------------------------------------------------

# <github.com/busyloop/lolcat>
gem "lolcat"

# -----------------------------------------------------------------------------
# Webdev/networking
# -----------------------------------------------------------------------------

gem "http"
gem "net-scp"
gem "net-ssh"
gem "nokogiri", ">= 1.10.10"

# <ipinfo.io>
gem "IPinfo"

# <github.com/middleman/middleman>
gem "middleman"

# <github.com/sass/sass>
gem "sassc"

# <github.com/slim-template/slim>
gem "slim"

# -----------------------------------------------------------------------------
# APIs
# -----------------------------------------------------------------------------

# <github.com/oauth-xx/oauth-ruby>
gem "oauth"

# <github.com/tumblr/tumblr_client>
gem "tumblr_client"

# -----------------------------------------------------------------------------
# Script requirements
# -----------------------------------------------------------------------------

# -- for BitBar weather app
# <github.com/trailblazer/representable>
gem "representable"

# -- for uu{char,debug,grep}
gem "gemoji"
gem "unicode_utils"

# -----------------------------------------------------------------------------
# local gems
# ----------------------------------------------------------------------------

gem "bunter", git: "git@github.com:zgracem/bunter.git"
gem "tiny_dancer", git: "git@github.com:zgracem/tiny-dancer.git"
gem "weather_meteo", path: "#{ENV['HOME']}/Dropbox/lib/ruby/weather_meteo"
