return ### ZGM disabled 2016-06-10 -- slow & not that helpful?

_inPath direnv || return

# use ~/.local
export DIRENV_CONFIG="$dir_local/direnv"

# don't show "direnv: un/loading" messages
export DIRENV_LOG_FORMAT=""

_direnv_hook()
{   # as would have been generated by `direnv hook bash`
    #   (if I weren't such a control freak)
    # and added to the beginning of PROMPT_COMMAND
    #   (the rest of which is set in prompt.bash)
    eval "$(direnv export bash)";
}

gitenv()
{ # set up git repo for direnv use
  local oldpwd="$PWD"

  if [[ $1 == -f ]]; then # force it
    printf "%s\n" "export Z_PROMPT_GIT=true;" | tee "$PWD/.envrc"
    direnv allow
    return
  fi

  until [[ -d $PWD/.git ]]; do
    builtin cd ..

    if [[ $PWD == / ]]; then
      scold "no git repository found"
      return 1
    fi
  done

  echo "> found $PWD/.git"

  if ! grep -Esq 'Z_PROMPT_GIT=true' "$PWD/.envrc"; then
    printf "%s\n" "export Z_PROMPT_GIT=true;" | tee "$PWD/.envrc"
    direnv allow
  else
    echo "> $PWD/.envrc OK"
  fi

  builtin cd "$oldpwd"
}
