# -----------------------------------------------------------------------------
# Erato:~/.local/config/brew/Brewfile
# vim:ft=ruby
# -----------------------------------------------------------------------------

# Instructions:
#   1. Install Homebrew
#   2. `brew tap homebrew/bundle`
#   3. `brew bundle --file=~/.config/brew/Brewfile`
#   4. `brew bundle --file=$THIS_FILE`

# -----------------------------------------------------------------------------

brew "agedu"
brew "ghostscript"
brew "imagemagick@6"
brew "pngcrush"
brew "youtube-dl"

# ffmpeg without options
brew "ffmpeg"
