# Use (and override) this in other files with:
#   extends: ../../.config/.markdownlint.yaml
---
# Enable all rules (default behaviour)
# default: true

# MD001: Heading levels should only increment by one level at a time
# heading-increment: true

# MD002: DNE

# MD003: Heading style consistency
# heading-style: true

# MD004: Unordered list style
# ul-style: true

# MD005: Inconsistent indentation for list items at the same level
list-indent: true

# MD006: DNE

# MD007: Unordered list indentation
ul-indent:
  indent: 4

# MD008: DNE

# MD009: Trailing spaces
no-trailing-spaces:
  list_item_empty_lines: true
  strict: true

# MD010: Hard tabs
no-hard-tabs:
  code_blocks: false
  spaces_per_tab: 4

# MD011: Reversed link syntax
# no-reversed-links: true

# MD012: Multiple consecutive blank lines
# no-multiple-blanks: true

# MD013: Line length
line-length: false

# MD014: Dollar signs used before commands without showing output
# commands-show-output: true

# MD015-17: DNE

# MD018-021: No/multiple spaces after/inside hash on atx-style heading
# no-missing-space-atx: true
# no-multiple-space-atx: true
# no-missing-space-closed-atx: true
# no-multiple-space-closed-atx: true

# MD022: Headings should be surrounded by blank lines
# blanks-around-headings: true

# MD023: Headings must start at the beginning of the line
# heading-start-left: true

# MD024: Multiple headings with the same content
no-duplicate-heading:
  siblings_only: true

# MD025: Multiple top level headings in the same document
single-title:
  front_matter_title: ^\s*(title|subject)\s*[:=]

# MD026: Trailing punctuation in heading
no-trailing-punctuation: false

# MD027: Multiple spaces after blockquote
# no-multiple-space-blockquote: true

# MD028: Blank line between two blockquotes
no-blanks-blockquote: false

# MD029: Ordered list item prefix
ol-prefix: false

# MD030: Spaces after list markers
# list-marker-space: true

# MD031: Fenced code blocks should be surrounded by blank lines
blanks-around-fences:
  list_items: false

# MD032: Lists should be surrounded by blank lines
# blanks-around-lists: true

# MD033: Inline HTML
no-inline-html: false

# MD034: Bare URL used
# no-bare-urls: true

# MD035: Horizontal rule style
# hr-style: true

# MD036: Emphasis used instead of a heading
no-emphasis-as-heading: false

# MD037-039: Spaces inside emphasis, code, and link spans
# no-space-in-emphasis: true
# no-space-in-code: true
# no-space-in-links: true

# MD040: Fenced code blocks should have a language specified
fenced-code-language: false

# MD041: First line in file should be a top level heading
first-line-heading: false

# MD042: No empty links
# no-empty-links: true

# MD043: Required heading structure
# required-headings: false

# MD044: Proper names should have the correct capitalization
# proper-names: false

# MD045: Images should have alternate text (alt text)
no-alt-text: false

# MD046: Code block style
# code-block-style: true

# MD047: Files should end with a single newline character
# single-trailing-newline: true

# MD048: Code fence style
# code-fence-style: true

# MD049: Emphasis style
# emphasis-style: true

# MD050: Strong style
# strong-style: true

# MD051: Link fragments should be valid
link-fragments:
  ignore_case: true

# MD052: Reference links and images should use a label that is defined
# reference-links-images: true

# MD053: Link and image reference definitions should be needed
# link-image-reference-definitions: true

# MD054: Link and image style
link-image-style:
  collapsed: false

# MD055: Table pipe style
table-pipe-style:
  style: leading_and_trailing

# MD056: Table column count
# table-column-count: true

# MD057: DNE

# MD058: Tables should be surrounded by blank lines
# blanks-around-tables: true

# MD059: Link text should be descriptive
descriptive-link-text: false
