complete -c my-prompt-pwd -a "(__fish_complete_directories)"
complete -c my-prompt-pwd -s g -l glyph -x -d "Symbol marking compression"
complete -c my-prompt-pwd -s G -l no-glyph -d "Do not use a symbol for compression"
complete -c my-prompt-pwd -s k -l keep-dirs -x -d "Keep N trailing dirnames unshortened"
complete -c my-prompt-pwd -s h -l keep-home -d "Compress \$HOME to ~"
complete -c my-prompt-pwd -s H -l no-keep-home -d "Skip compressing \$HOME to ~"
complete -c my-prompt-pwd -s m -l min-part -x -d "Never shorten dirnames ≤N chars"
complete -c my-prompt-pwd -s M -l max-part -x -d "Always shorten dirnames ≥N chars"
complete -c my-prompt-pwd -s P -l max-path -x -d "Don't shorten path if ≤N chars"
complete -c my-prompt-pwd -s c -l collapse -d "Collapse fully compressed dirnames"
complete -c my-prompt-pwd -s r -l repo -d "Skip shortening git repos"
complete -c my-prompt-pwd -s R -l no-repo -d "Don't skip shortening git repos"
complete -c my-prompt-pwd -s V -l vanilla -d "Act like default fish prompt_pwd"
complete -c my-prompt-pwd -s Z -l no-short -d "Disable dirname shortening"
complete -c my-prompt-pwd -s z -l shortest -d "Shorten almost everything"
