function _errno_posix -a num
  test "$num" -le 133
  or return

  # Source: https://nuetzlich.net/errno.html
  set -l posix_errno PERM NOENT SRCH INTR IO NXIO 2BIG NOEXEC BADF CHILD AGAIN \
                     NOMEM ACCES FAULT NOTBLK BUSY EXIST XDEV NODEV NOTDIR \
                     ISDIR INVAL NFILE MFILE NOTTY TXTBSY FBIG NOSPC SPIPE \
                     ROFS MLINK PIPE DOM RANGE DEADLK NAMETOOLONG NOLCK NOSYS \
                     NOTEMPTY LOOP WOULDBLOCK NOMSG IDRM CHRNG L2NSYNC L3HLT \
                     L3RST LNRNG UNATCH NOCSI L2HLT BADE BADR XFULL NOANO \
                     BADRQC BADSLT DEADLOCK BFONT NOSTR NODATA TIME NOSR NONET \
                     NOPKG REMOTE NOLINK ADV SRMNT COMM PROTO MULTIHOP DOTDOT \
                     BADMSG OVERFLOW NOTUNIQ BADFD REMCHG LIBACC LIBBAD LIBSCN \
                     LIBMAX LIBEXEC ILSEQ RESTART STRPIPE USERS NOTSOCK \
                     DESTADDRREQ MSGSIZE PROTOTYPE NOPROTOOPT PROTONOSUPPORT \
                     SOCKTNOSUPPORT OPNOTSUPP PFNOSUPPORT AFNOSUPPORT \
                     ADDRINUSE ADDRNOTAVAIL NETDOWN NETUNREACH NETRESET \
                     CONNABORTED CONNRESET NOBUFS ISCONN NOTCONN SHUTDOWN \
                     TOOMANYREFS TIMEDOUT CONNREFUSED HOSTDOWN HOSTUNREACH \
                     ALREADY INPROGRESS STALE UCLEAN NOTNAM NAVAIL ISNAM \
                     REMOTEIO DQUOT NOMEDIUM MEDIUMTYPE CANCELED NOKEY \
                     KEYEXPIRED KEYREVOKED KEYREJECTED OWNERDEAD \
                     NOTRECOVERABLE RFKILL HWPOISON

  # {{{
    set -l ePERM "Operation not permitted"
    set -l eNOENT "No such file or directory"
    set -l eSRCH "No such process"
    set -l eINTR "Interrupted system call"
    set -l eIO "I/O error"
    set -l eNXIO "No such device or address"
    set -l e2BIG "Argument list too long"
    set -l eNOEXEC "Exec format error"
    set -l eBADF "Bad file number"
    set -l eCHILD "No child processes"
    set -l eAGAIN "Try again"
    set -l eNOMEM "Out of memory"
    set -l eACCES "Permission denied"
    set -l eFAULT "Bad address"
    set -l eNOTBLK "Block device required"
    set -l eBUSY "Device or resource busy"
    set -l eEXIST "File exists"
    set -l eXDEV "Cross-device link"
    set -l eNODEV "No such device"
    set -l eNOTDIR "Not a directory"
    set -l eISDIR "Is a directory"
    set -l eINVAL "Invalid argument"
    set -l eNFILE "File table overflow"
    set -l eMFILE "Too many open files"
    set -l eNOTTY "Not a typewriter"
    set -l eTXTBSY "Text file busy"
    set -l eFBIG "File too large"
    set -l eNOSPC "No space left on device"
    set -l eSPIPE "Illegal seek"
    set -l eROFS "Read-only file system"
    set -l eMLINK "Too many links"
    set -l ePIPE "Broken pipe"
    set -l eDOM "Math argument out of domain of func"
    set -l eRANGE "Math result not representable"
    set -l eDEADLK "Resource deadlock would occur"
    set -l eNAMETOOLONG "File name too long"
    set -l eNOLCK "No record locks available"
    set -l eNOSYS "Invalid system call number"
    set -l eNOTEMPTY "Directory not empty"
    set -l eLOOP "Too many symbolic links encountered"
    set -l eWOULDBLOCK "Operation would block"
    set -l eNOMSG "No message of desired type"
    set -l eIDRM "Identifier removed"
    set -l eCHRNG "Channel number out of range"
    set -l eL2NSYNC "Level 2 not synchronized"
    set -l eL3HLT "Level 3 halted"
    set -l eL3RST "Level 3 reset"
    set -l eLNRNG "Link number out of range"
    set -l eUNATCH "Protocol driver not attached"
    set -l eNOCSI "No CSI structure available"
    set -l eL2HLT "Level 2 halted"
    set -l eBADE "Invalid exchange"
    set -l eBADR "Invalid request descriptor"
    set -l eXFULL "Exchange full"
    set -l eNOANO "No anode"
    set -l eBADRQC "Invalid request code"
    set -l eBADSLT "Invalid slot"
    set -l eDEADLOCK "DEADLK"
    set -l eBFONT "Bad font file format"
    set -l eNOSTR "Device not a stream"
    set -l eNODATA "No data available"
    set -l eTIME "Timer expired"
    set -l eNOSR "Out of streams resources"
    set -l eNONET "Machine is not on the network"
    set -l eNOPKG "Package not installed"
    set -l eREMOTE "Object is remote"
    set -l eNOLINK "Link has been severed"
    set -l eADV "Advertise error"
    set -l eSRMNT "Srmount error"
    set -l eCOMM "Communication error on send"
    set -l ePROTO "Protocol error"
    set -l eMULTIHOP "Multihop attempted"
    set -l eDOTDOT "RFS specific error"
    set -l eBADMSG "Not a data message"
    set -l eOVERFLOW "Value too large for defined data type"
    set -l eNOTUNIQ "Name not unique on network"
    set -l eBADFD "File descriptor in bad state"
    set -l eREMCHG "Remote address changed"
    set -l eLIBACC "Can not access a needed shared library"
    set -l eLIBBAD "Accessing a corrupted shared library"
    set -l eLIBSCN ".lib section in a.out corrupted"
    set -l eLIBMAX "Attempting to link in too many shared libraries"
    set -l eLIBEXEC "Cannot exec a shared library directly"
    set -l eILSEQ "Illegal byte sequence"
    set -l eRESTART "Interrupted system call should be restarted"
    set -l eSTRPIPE "Streams pipe error"
    set -l eUSERS "Too many users"
    set -l eNOTSOCK "Socket operation on non-socket"
    set -l eDESTADDRREQ "Destination address required"
    set -l eMSGSIZE "Message too long"
    set -l ePROTOTYPE "Protocol wrong type for socket"
    set -l eNOPROTOOPT "Protocol not available"
    set -l ePROTONOSUPPORT "Protocol not supported"
    set -l eSOCKTNOSUPPORT "Socket type not supported"
    set -l eOPNOTSUPP "Operation not supported on transport endpoint"
    set -l ePFNOSUPPORT "Protocol family not supported"
    set -l eAFNOSUPPORT "Address family not supported by protocol"
    set -l eADDRINUSE "Address already in use"
    set -l eADDRNOTAVAIL "Cannot assign requested address"
    set -l eNETDOWN "Network is down"
    set -l eNETUNREACH "Network is unreachable"
    set -l eNETRESET "Network dropped connection because of reset"
    set -l eCONNABORTED "Software caused connection abort"
    set -l eCONNRESET "Connection reset by peer"
    set -l eNOBUFS "No buffer space available"
    set -l eISCONN "Transport endpoint is already connected"
    set -l eNOTCONN "Transport endpoint is not connected"
    set -l eSHUTDOWN "Cannot send after transport endpoint shutdown"
    set -l eTOOMANYREFS "Too many references: cannot splice"
    set -l eTIMEDOUT "Connection timed out"
    set -l eCONNREFUSED "Connection refused"
    set -l eHOSTDOWN "Host is down"
    set -l eHOSTUNREACH "No route to host"
    set -l eALREADY "Operation already in progress"
    set -l eINPROGRESS "Operation now in progress"
    set -l eSTALE "Stale file handle"
    set -l eUCLEAN "Structure needs cleaning"
    set -l eNOTNAM "Not a XENIX named type file"
    set -l eNAVAIL "No XENIX semaphores available"
    set -l eISNAM "Is a named type file"
    set -l eREMOTEIO "Remote I/O error"
    set -l eDQUOT "Quota exceeded"
    set -l eNOMEDIUM "No medium found"
    set -l eMEDIUMTYPE "Wrong medium type"
    set -l eCANCELED "Operation Canceled"
    set -l eNOKEY "Required key not available"
    set -l eKEYEXPIRED "Key has expired"
    set -l eKEYREVOKED "Key has been revoked"
    set -l eKEYREJECTED "Key was rejected by service"
    set -l eOWNERDEAD "Owner died"
    set -l eNOTRECOVERABLE "State not recoverable"
    set -l eRFKILL "Operation not possible due to RF-kill"
    set -l eHWPOISON "Memory page has hardware error"
  # }}}

  set -l posix_error $posix_errno[$num]
  echo -es "E" $posix_error "\n    " (eval "echo \$e$posix_error") "."
end
