function _errno_curl -a num
  set -l curl_errors
    set curl_errors[1] "Unsupported protocol"
    set curl_errors[2] "Failed to initialize"
    set curl_errors[3] "URL malformed"
    set curl_errors[4] "Missing build-time feature"
    set curl_errors[5] "Couldn't resolve proxy"
    set curl_errors[6] "Couldn't resolve host"
    set curl_errors[7] "Failed to connect to host"
    set curl_errors[8] "Weird server reply"
    set curl_errors[9] "FTP access denied"
    set curl_errors[10] "FTP accept failed"
    set curl_errors[11] "FTP weird PASS reply"
    set curl_errors[12] "Active FTP session timed out waiting for the server to connect back to curl"
    set curl_errors[13] "FTP weird PASV reply"
    set curl_errors[14] "FTP weird 227 format"
    set curl_errors[15] "FTP can't get host"
    set curl_errors[16] "HTTP/2 error"
    set curl_errors[17] "FTP couldn't set binary"
    set curl_errors[18] "Partial file"
    set curl_errors[19] "FTP couldn't download/access the given file"
    set curl_errors[21] "FTP quote error"
    set curl_errors[22] "HTTP page not retrieved"
    set curl_errors[23] "Write error"
    set curl_errors[25] "FTP couldn't STOR file"
    set curl_errors[26] "Read error"
    set curl_errors[27] "Out of memory"
    set curl_errors[28] "Operation timeout"
    set curl_errors[30] "FTP PORT failed"
    set curl_errors[31] "FTP couldn't use REST"
    set curl_errors[33] "HTTP range error"
    set curl_errors[34] "HTTP post error"
    set curl_errors[35] "SSL connect error"
    set curl_errors[36] "Bad download resume"
    set curl_errors[37] "FILE couldn't read file"
    set curl_errors[38] "LDAP cannot bind"
    set curl_errors[39] "LDAP search failed"
    set curl_errors[41] "Function not found"
    set curl_errors[42] "Aborted by callback"
    set curl_errors[43] "Internal error"
    set curl_errors[45] "Interface error"
    set curl_errors[47] "Too many redirects"
    set curl_errors[48] "Unknown option specified to libcurl"
    set curl_errors[49] "Malformed telnet option"
    set curl_errors[51] "The peer's SSL certificate or SSH MD5 fingerprint was not OK"
    set curl_errors[52] "The server didn't reply anything"
    set curl_errors[53] "SSL crypto engine not found"
    set curl_errors[54] "Cannot set SSL crypto engine as default"
    set curl_errors[55] "Failed sending network data"
    set curl_errors[56] "Failure in receiving network data"
    set curl_errors[58] "Problem with the local certificate"
    set curl_errors[59] "Couldn't use specified SSL cipher"
    set curl_errors[60] "Peer certificate cannot be authenticated with known CA certificates"
    set curl_errors[61] "Unrecognized transfer encoding"
    set curl_errors[62] "Invalid LDAP URL"
    set curl_errors[63] "Maximum file size exceeded"
    set curl_errors[64] "Requested FTP SSL level failed"
    set curl_errors[65] "Sending the data requires a rewind that failed"
    set curl_errors[66] "Failed to initialise SSL Engine"
    set curl_errors[67] "Login failed: user name, password, or similar was not accepted"
    set curl_errors[68] "File not found on TFTP server"
    set curl_errors[69] "Permission problem on TFTP server"
    set curl_errors[70] "Out of disk space on TFTP server"
    set curl_errors[71] "Illegal TFTP operation"
    set curl_errors[72] "Unknown TFTP transfer ID"
    set curl_errors[73] "File already exists (TFTP)"
    set curl_errors[74] "No such user (TFTP)"
    set curl_errors[75] "Character conversion failed"
    set curl_errors[76] "Character conversion functions required"
    set curl_errors[77] "Problem with reading the SSL CA cert (path? access rights?)"
    set curl_errors[78] "The resource referenced in the URL does not exist"
    set curl_errors[79] "An unspecified error occurred during the SSH session"
    set curl_errors[80] "Failed to shut down the SSL connection"
    set curl_errors[82] "Could not load CRL file, missing or wrong format"
    set curl_errors[83] "Issuer check failed"
    set curl_errors[84] "The FTP PRET command failed"
    set curl_errors[85] "RTSP: mismatch of CSeq numbers"
    set curl_errors[86] "RTSP: mismatch of Session Identifiers"
    set curl_errors[87] "unable to parse FTP file list"
    set curl_errors[88] "FTP chunk callback reported error"
    set curl_errors[89] "No connection available, the session will be queued"
    set curl_errors[90] "SSL public key does not matched pinned public key"

  if test -n "$curl_errors[$num]"
    set curl_err $curl_errors[$num]
    echo -es "curl error" "\n    " $curl_err "."
  end
end
