# the silver searcher
complete -c ag      -l ackmate -d 'Print results in AckMate-parseable format'
complete -c ag      -l affinity -d 'Set thread affinity (if platform supports)'
complete -c ag      -l noaffinity -d 'Don\'t set thread affinity'
complete -c ag -s A -l after -x -d 'Print lines after match (def: 2)'
complete -c ag -s t -l all-text -d 'Search all text files (not hidden files)'
complete -c ag -s a -l all-types -d 'Search all files (not hidden or .*ignore\'d files)'
complete -c ag -s B -l before -x -d 'Print lines before match (def: 2)'
complete -c ag      -l break -d 'Print newlines between matches in different files'
complete -c ag      -l nobreak -d 'Don\'t print newlines between matches in different files'
complete -c ag -s s -l case-sensitive -d 'Match case sensitively'
complete -c ag      -l color -d 'Print color codes in results'
complete -c ag      -l nocolor -d 'Don\'t print color codes in results'
complete -c ag      -l color-line-number -xa '1;33' -d 'Color codes for line numbers (def: 1;33)'
complete -c ag      -l color-match -xa '30;43' -d 'Color codes for result match numbers (def: 30;43)'
complete -c ag      -l color-path -xa '1;32' -d 'Color codes for path names (def: 1;32)'
complete -c ag      -l column -d 'Print column numbers in results'
complete -c ag -s C -l context -d 'Print lines before and after matches (def: 2)'
complete -c ag -s c -l count -d 'Only print the number of matches in each file'
complete -c ag -s D -l debug -d 'Ridiculous debugging'
complete -c ag      -l depth -x -d 'Search up to NUM directories deep (def: 25)'
complete -c ag -s G -l file-search-regex -x -d 'Limit search to filenames matching PATTERN'
complete -c ag      -l filename -d 'Print file names'
complete -c ag      -l nofilename -d 'Don\'t print file names'
complete -c ag -s g -l filename-pattern -x -d 'Print filenames matching PATTERN'
complete -c ag -s l -l files-with-matches -d 'Don\'t print matching lines'
complete -c ag -s L -l files-without-matches -d 'Only print filenames without matches'
complete -c ag -s f -l follow -d 'Follow symlinks'
complete -c ag      -l nofollow -d 'Don\'t follow symlinks'
complete -c ag      -l group -d 'Group matches from the same file'
complete -c ag      -l nogroup -d 'Don\'t group matches from the same file'
complete -c ag -s H -l heading -d 'Print filenames before each file\'s matches'
complete -c ag      -l noheading -d 'Don\'t print filenames before matches'
complete -c ag      -l hidden -d 'Search hidden files (obeys .*ignore files)'
complete -c ag      -l ignore -l ignore-dir -d 'Ignore files/directories matching PATTERN'
complete -c ag -s i -l ignore-case -d 'Match case insensitively'
complete -c ag -s v -l invert-match -d 'Invert match'
complete -c ag -s Q -l literal -l fixed-strings -x -d 'Don\'t parse PATTERN as a regex'
complete -c ag -s m -l max-count -x -d 'Skip the rest of a file after NUM matches (def: 10,000)'
complete -c ag      -l mmap -d 'Use memory-mapped I/O'
complete -c ag      -l nommap -d 'Don\'t use memory-mapped I/O'
complete -c ag      -l multiline -d 'Match regexes across newlines'
complete -c ag      -l nomultiline -d 'Don\'t match regexes across newlines'
complete -c ag -s 0 -l null -l print0 -d 'Separate filenames with null'
complete -c ag      -l numbers -d 'Print line numbers'
complete -c ag      -l nonumbers -d 'Don\'t print line numbers'
complete -c ag      -l one-device -d 'Don\'t follow links to other devices'
complete -c ag -s o -l only-matching -d 'Prints only the matching part of the lines'
complete -c ag      -l pager -r -d 'Use a pager such as less'
complete -c ag      -l nopager -d 'Don\'t use a pager'
complete -c ag      -l passthrough -l passthru -d 'When searching a stream, print even non-matching lines'
complete -c ag -s p -l path-to-ignore -r -d 'Use .*ignore file at STRING'
complete -c ag      -l print-all-files -d 'Print headings for all files, even non-matching'
complete -c ag      -l print-long-lines -d 'Print matches on very long lines (def: >2k chars)'
complete -c ag      -l search-binary -d 'Search binary files for matches'
complete -c ag -s z -l search-zip -d 'Search compressed files'
complete -c ag      -l silent -d 'Suppress all log messages, including errors'
complete -c ag -s U -l skip-vcs-ignores -d 'Ignore VCS .*ignore files'
complete -c ag -s S -l smart-case -d 'Match case insensitively unless PATTERN contains uppercase characters'
complete -c ag      -l stats -d 'Print stats'
complete -c ag      -l stats-only -d 'Print only stats'
complete -c ag -s u -l unrestricted -d 'Search all files'
complete -c ag      -l vimgrep -d 'Print results like :vimgrep /pattern/g'
complete -c ag -s W -l width -x -d 'Truncate match lines after NUM characters'
complete -c ag -s w -l word-regexp -d 'Only match whole words'
