# Visual Studio Code
# Generated using help2man and fish_update_completions
complete -c code -s d -l diff -d 'Compare two files with each other'
complete -c code -s a -l add -d 'Add folder(s) to the last active window'
complete -c code -s g -l goto -d 'line and character position'
complete -c code -s n -l new-window -d 'Force to open a new window'
complete -c code -s r -l reuse-window -d 'Force to open a file or folder in an already opened window'
complete -c code -s w -l wait -d 'Wait for the files to be closed before returning'
complete -c code -l locale -d 'The locale to use (e.g. en-US or zh-TW)'
complete -c code -l user-data-dir -d 'Specifies the directory that user data is kept in'
complete -c code -s v -l version -d 'Print version'
complete -c code -s h -l help -d 'Print usage'
complete -c code -l folder-uri -d 'Opens a window with given folder uri(s)'
complete -c code -l file-uri -d 'Opens a window with given file uri(s)'
complete -c code -l extensions-dir -d 'Set the root path for extensions'
complete -c code -l list-extensions -d 'List the installed extensions'
complete -c code -l show-versions -d 'Show versions of installed extensions, when using --list-extension'
complete -c code -l install-extension -d 'Installs or updates the extension.  Use `--force` argument to avoid prompts'
complete -c code -l enable-proposed-api -d 'extensions.  Can receive one or more extension IDs to enable individually'
complete -c code -l verbose -d 'Print verbose output (implies --wait)'
complete -c code -l log -d 'Log level to use.  Default is \'info\''
complete -c code -s s -l status -d 'Print process usage and diagnostics information'
complete -c code -s p -l prof-modules -d 'Capture performance markers while loading JS modules and print them with F1…'
complete -c code -l prof-startup -d 'Run CPU profiler during startup'
complete -c code -l disable-extensions -d 'Disable all installed extensions'
complete -c code -l inspect-extensions -d 'Allow debugging and profiling of extensions'
complete -c code -l inspect-brk-extensions -d 'Allow debugging and profiling of extensions with the extension host being pau…'
complete -c code -l disable-gpu -d 'Disable GPU hardware acceleration'
complete -c code -l upload-logs -d 'Uploads logs from current session to a secure endpoint'
complete -c code -l uninstall-extension
complete -c code -l disable-extension
complete -c code -l max-memory -d 'Max memory size for a window (in Mbytes)'
