# cygstart
# Generated using help2man and fish_update_completions

complete -c cygstart -s a -l action -r -a 'open explore edit find print' -d 'Use specified action instead of default'
complete -c cygstart -s o -l open -d 'Short for: --action open'
complete -c cygstart -s x -l explore -d 'Short for: --action explore'
complete -c cygstart -s e -l edit -d 'Short for: --action edit'
complete -c cygstart -s f -l find -d 'Short for: --action find'
complete -c cygstart -s p -l print -d 'Short for: --action print'
complete -c cygstart -s d -l directory -r -d 'Set working directory'
complete -c cygstart -l hide -d 'Hides the window and activates another window'
complete -c cygstart -l maximize -d 'Maximizes the specified window'
complete -c cygstart -l minimize -d 'Minimizes the specified window and activates the next top-level window in the…'
complete -c cygstart -l restore -d 'Activates and displays the window'
complete -c cygstart -l show -d 'Activates the window and displays it in its current size and position'
complete -c cygstart -l showmaximized -d 'Activates the window and displays it as a maximized window'
complete -c cygstart -l showminimized -d 'Activates the window and displays it as a minimized window'
complete -c cygstart -l showminnoactive -d 'Displays the window as a minimized window'
complete -c cygstart -l showna -d 'Displays the window in its current state'
complete -c cygstart -l shownoactivate -d 'Displays a window in its most recent size and position'
complete -c cygstart -l shownormal -d 'Activates and displays a window'
complete -c cygstart -s w -l wait -d 'Waits until the started application terminates before exiting'
complete -c cygstart -s v -l verbose -d 'Show the actual ShellExecute call made'
complete -c cygstart -s '?' -l help -d 'Show this help message'
complete -c cygstart -l usage -d 'Display brief usage message'
complete -c cygstart -l version -d 'Display version information'
complete -c cygstart -l license -d 'Display licensing information'
complete -c cygstart -l reference -d 'Open MSDN reference for ShellExecute'
