complete -c help2man -s n -l name -x -d 'description for the "NAME" paragraph'
complete -c help2man -s s -l section -xa '1 6 8' -d 'section number for manual page'
complete -c help2man -s m -l manual -xa 'User\ Commands' -d 'name of manual'
complete -c help2man -s S -l source -xa 'FSF Debian' -d 'source of program'
complete -c help2man -s L -l locale -xa '(locale -a)' -d 'select locale (default "C")'
complete -c help2man -s i -l include -r -d 'include material from FILE'
complete -c help2man -s I -l opt-include -r -d 'include material from FILE if it exists'
complete -c help2man -s o -l output -r -d 'send output to FILE'
complete -c help2man -s p -l info-page -x -d 'name of Texinfo manual'
complete -c help2man -s N -l no-info -d 'suppress pointer to Texinfo manual'
complete -c help2man -s l -l libtool -d 'exclude the "lt-" from the program name'
complete -c help2man -l help -d 'print this help, then exit'
complete -c help2man -l version -d 'print version, then exit'
complete -c help2man -s h -l help-option -xa '-h -help' -d 'help option string'
complete -c help2man -s v -l version-option -xa '-v -version' -d 'version option string'
complete -c help2man -l version-string -d 'version string'
complete -c help2man -l no-discard-stderr -d 'include stderr when parsing option output'
