complete -c hexyl -s n -l length -s c -l bytes -s l -x -d 'Read only N bytes'
complete -c hexyl -s s -l skip -d 'Skip first N bytes of input'
complete -c hexyl -l block-size -x -d 'Set block size to N bytes'
complete -c hexyl -s v -l no-squeezing -d 'Display all input data'
complete -c hexyl -l color -xa 'always auto never' -d 'When to use color'
complete -c hexyl -l border -xa 'unicode ascii none' -d 'How to draw border'
complete -c hexyl -s o -l display-offset -x -d 'Add N bytes to display position'
complete -c hexyl -s h -l help -d 'Print help'
complete -c hexyl -s V -l version -d 'Print version'
