complete -c nethack -s d -d 'specify a playground directory'
complete -c nethack -s n -d 'suppress printing any news from the game administrator'
complete -c nethack -s p -d 'specify profession'
complete -c nethack -s r -d 'specify race'
complete -c nethack -s D -d 'start in debugging (wizard) mode'
complete -c nethack -s X -d 'start in discovery mode'
complete -c nethack -s u -d 'specify player name'
complete -c nethack -o dec -d 'use DEC graphics'
complete -c nethack -o ibm -d 'use IBM graphics'
complete -c nethack -l version -d 'show version information'
complete -c nethack -l version:paste -d 'show version information & copy it to paste buffer'
complete -c nethack -s s -d 'print the list of your scores'
complete -c nethack -s v -d 'print all versions present in the score file'
