complete -c scan -a wifi -d 'List all public SSIDs nearby'
complete -c scan -a ssh -d 'List all SSH-enabled hosts on the current domain'
complete -c scan -a port -d 'Track access on <port>'
complete -c scan -a pid -d 'Track access by process ID'
complete -c scan -a fs -d 'Continuous stream of file system access info'
complete -c scan -a file -d 'Track access to a file'
