complete -c screenfetch -s v --description 'Verbose output'
complete -c screenfetch -s o --description 'Set script variables on the command line'
complete -c screenfetch -s d --description 'Set what information is displayed on the command line'
complete -c screenfetch -s n --description 'Do not display ASCII distribution logo'
complete -c screenfetch -s L --description 'Display ASCII distribution logo only'
complete -c screenfetch -s N --description 'Strip all color from output'
complete -c screenfetch -s w --description 'Wrap long lines'
complete -c screenfetch -s t --description 'Truncate output based on terminal width (Experimental!)'
complete -c screenfetch -s p --description 'Output in portrait mode, with logo above info'
complete -c screenfetch -s s --description 'Take a screenshot'
complete -c screenfetch -s u --description 'Specify an image host'
complete -c screenfetch -s c --description 'Change the outputted colors'
complete -c screenfetch -s a --description 'Specify custom ASCII art'
complete -c screenfetch -s S --description 'Specify a custom screenshot command'
complete -c screenfetch -s D --description 'Specify your distribution'
complete -c screenfetch -s A --description 'Specify the distribution art'
complete -c screenfetch -s E --description 'Suppress output of errors'
complete -c screenfetch -s V -l version --description 'Display current script version'
complete -c screenfetch -s h -l help --description 'Display this help'
