complete -c ssh-add -s C -d 'Only process certificates'
complete -c ssh-add -s c -d 'Confirm added identities'
complete -c ssh-add -s D -d 'Delete all identities'
complete -c ssh-add -s d -d 'Remove identities'
complete -c ssh-add -s E -x -a "md5 sha256" -d 'Hash algorithm for key fingerprints'
complete -c ssh-add -s e -x -d 'Remove keys provided by PKCS#11 shared library'
complete -c ssh-add -s H -rF -d 'Use known_hosts file'
complete -c ssh-add -s h -x -d 'Constrain keys to specific destinations'
complete -c ssh-add -s K -d 'Load resident keys from a FIDO authenticator'
complete -c ssh-add -s k -d 'Only process private keys'
complete -c ssh-add -s L -d 'List all public key parameters'
complete -c ssh-add -s l -d 'List all fingerprints'
complete -c ssh-add -s q -d 'Be quiet after successful operation'
complete -c ssh-add -s S -rF -d 'Path to FIDO auth library'
complete -c ssh-add -s s -x -d 'Add keys provided by PKCS#11 shared library'
complete -c ssh-add -s T -rF -d 'Test private keys for these public keys'
complete -c ssh-add -s t -x -d 'Set maximum identity lifetime'
complete -c ssh-add -s v -d 'Verbose mode'
complete -c ssh-add -s X -d 'Unlock agent'
complete -c ssh-add -s x -d 'Lock agent with password'
