# unar <https://unarchiver.c3.cx/commandline>

complete -c unar -s o -o output-directory -r -d 'The directory to write the contents of the archive to'
complete -c unar -s f -o force-overwrite -d 'Always overwrite files when a file to be unpacked already exists on disk'
complete -c unar -s r -o force-rename -d 'Always rename files when a file to be unpacked already exists on disk'
complete -c unar -s s -o force-skip -d 'Always skip files when a file to be unpacked already exists on disk'
complete -c unar -s d -o force-directory -d 'Always create a containing directory for the contents of the unpacked archive'
complete -c unar -s D -o no-directory -d 'Never create a containing directory for the contents of the unpacked archive'
complete -c unar -s p -o password -x -d 'The password to use for decrypting protected archives'
complete -c unar -s e -o encoding -x -d 'The encoding to use for filenames in the archive'
complete -c unar -s E -o password-encoding -x -d 'The encoding to use for the password for the archive'
complete -c unar -s i -o indexes -d 'Specify the files to list by lsar index'
complete -c unar -o nr -o no-recursion -d 'Do not attempt to extract archives contained in other archives'
complete -c unar -s t -o copy-time -d 'Copy the modification time from the archive file'
complete -c unar -o nq -o no-quarantine -d 'Do not copy Finder quarantine metadata from the archive'
complete -c unar -s k -o forks -xa 'fork visible hidden skip' -d 'How to handle macOS resource forks'
complete -c unar -s q -o quiet -d 'Run in quiet mode'
complete -c unar -s v -o version 'Print version and exit'
complete -c unar -s h -o help -d 'Display help information'
