complete -c vsdeploy -s p -d 'Only fix permissions'
complete -c vsdeploy -s s -d 'Only sync source w/ server'
complete -c vsdeploy -s m -d 'Only sync media w/ server'
complete -c vsdeploy -s b -d 'Only build on server'
complete -c vsdeploy -s d -d 'Sync source and build docs on server'
