# ----------------------------------------------------------------------------
# MacOS
# ----------------------------------------------------------------------------

include ../common.mk

# Create symlinks in $HOME/Library/Application Support
.PHONY: appsupport
appsupport:
	$(XDG_CONFIG_HOME)/macos/appsupport.sh
install: appsupport
