# ----------------------------------------------------------------------------
# bat: install and/or (re)build syntaxes
# ----------------------------------------------------------------------------

include ../common.mk

install: $(XDG_CACHE_HOME)/bat/syntaxes.bin
$(XDG_CACHE_HOME)/bat/syntaxes.bin:
	$(XDG_CONFIG_HOME)/libexec/bat-syntaxes.fish
