# -----------------------------------------------------------------------------
# ~zozo/.config/homebrew/Brewfile
# say hello: printf "zozo\x40inescapable\x2eorg"
# -----------------------------------------------------------------------------

# fetch the newest version of Homebrew and all formulae from GitHub
update

# -----------------------------------------------------------------------------
# shells
# -----------------------------------------------------------------------------

# bash 4
install bash
install bash-completion

# zsh
#install zsh

# fish
#install fish

# -----------------------------------------------------------------------------
# essentials
# -----------------------------------------------------------------------------

install python
install vim --HEAD

# git
install git
install hub

# tmux
install tmux
install reattach-to-user-namespace

# -----------------------------------------------------------------------------
# GNU utilities
# -----------------------------------------------------------------------------

# core utilities
install coreutils

# more utilities
install moreutils

# find, locate, updatedb, and xargs (do not prepend 'g' to the binaries)
install findutils --default-names

# sed (overwrite built-in)
install gnu-sed --default-names

# grep (overwrite built-in)
install homebrew/dupes/grep --default-names

# tar
install gnu-tar

# -----------------------------------------------------------------------------
# internet stuff
# -----------------------------------------------------------------------------

install links
install mobile-shell
install transmission
install ttytter
install wget --enable-iri
install homebrew/dupes/rsync
install homebrew/dupes/whois

# cURL
install curl --with-ssh

# email
#install alpine
install dovecot
install offline-imap

# GnuPG
install gnupg
install gpg-agent
install pinentry

# -----------------------------------------------------------------------------
# fun & games
# -----------------------------------------------------------------------------

install cowsay
install figlet
install homebrew/games/nethack
install homebrew/games/unnethack

# -----------------------------------------------------------------------------
# misc.
# -----------------------------------------------------------------------------

install ack
install aspell
install dict
install dos2unix
install dtrx
install jq
install multimarkdown
install node
install p7zip
install recode
install rename
install sqlite
install the_silver_searcher
install tree
install unrar
install watch
install homebrew/dupes/ncurses

# images
install imagemagick
install imagesnap || true # (imagesnap won't compile w/out Xcode.app)
install pngcrush
install webkit2png

# less
install homebrew/dupes/less
install source-highlight

# OpenSSL/OpenSSH
install openssl
link --force openssl
install homebrew/dupes/openssh --with-keychain-support
install ssh-copy-id

# audio/video
install atomicparsley
install ffmpeg --with-openssl --with-rtmpdump
install id3v2
install lame
install mp4v2
install mplayer
install youtube-dl --with-rtmpdump

# pdf
install ghostscript
install qpdf
install xpdf

# -----------------------------------------------------------------------------
# casks
# -----------------------------------------------------------------------------

#install phinze/cask/brew-cask

#cask install adium
#cask install alfred
#cask install back-in-time
#cask install betterzipql
#cask install disk-inventory-x
#cask install dropbox
#cask install fission
#cask install flux
#cask install github
#cask install google-chrome
#cask install google-drive
#cask install grandperspective
#cask install handbrake
#cask install id3-editor
#cask install imageoptim
#cask install ios7-screensaver
#cask install istat-menus
#cask install iterm2
#cask install jawbone-updater
#cask install monolingual
#cask install name-mangler
#cask install nvalt
#cask install onepassword
#cask install qlcolorcode
#cask install qlmarkdown
#cask install rdio
#cask install skype
#cask install transmission
#cask install transmit
#cask install vlc

#cask alfred link

# -----------------------------------------------------------------------------
# done
# -----------------------------------------------------------------------------

# remove old versions from the cellar
cleanup
