# ----------------------------------------------------------------------------
# $HOMEBREW_BUNDLE_FILE_GLOBAL
# vim:ft=ruby
# ----------------------------------------------------------------------------

if OS.mac?
  tap "nrlquaker/createzap", trusted: true # `brew createzap` command
  cask_args appdir: "~/Applications" # also set in HOMEBREW_CASK_OPTS
end

tap "zgracem/commands", "~/Developer/Homebrew/homebrew-commands", trusted: true
tap "zgracem/formulae", "~/Developer/Homebrew/homebrew-formulae", trusted: true

# ----------------------------------------------------------------------------
# essentials
# ----------------------------------------------------------------------------

if OS.mac?
  # GNU utilities
  brew "coreutils"
  brew "diffutils"
  brew "findutils"
  brew "gawk"
  brew "gnu-sed"
  brew "gnu-tar"
  brew "grep"
  brew "m4"

  # etc.
  brew "openssh"
  brew "openssl@3"
  brew "p7zip"
  brew "readline"
  brew "rename"
  brew "rsync"
  brew "pam-reattach" # for tmux
end

if OS.linux?
  brew "gcc"
  brew "make"
end

brew "bat", postinstall: "${HOMEBREW_PREFIX}/bin/bat cache --build"
brew "eza"
brew "fd"
brew "fish"
brew "jq"
brew "keychain" unless OS.mac?
brew "less"
brew "micro"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "vim-classic"

# ----------------------------------------------------------------------------
# more utilities
# ----------------------------------------------------------------------------

if OS.mac?
  brew "bash"
  brew "bchunk" # Convert CD images from .bin/.cue to .iso/.cdr
  brew "duti"
  brew "ncurses"
  brew "qrencode"
  brew "sf-pwgen"
  brew "tzdb"
end

brew "bfs" # Breadth-first version of find
brew "btop"
brew "cyme"
brew "ddrescue"
brew "entr"
brew "hexyl"
brew "parallel"
brew "PotatoLabs/git-redate/git-redate", trusted: true
brew "sponge"
brew "tree"

### text & documentation

brew "dos2unix"
brew "ghostscript"
brew "groff"
brew "zgracem/formulae/groff-pdfmark", trusted: true
brew "help2man"
brew "alhadis/troff/man-db", trusted: true if OS.mac?
brew "multimarkdown"
brew "pandoc"
brew "par"
brew "poppler" # PDF rendering library
brew "qpdf"
brew "recode"

### audio/video

brew "atomicparsley"
brew "audiowaveform"
brew "cdrdao"
brew "ffmpeg-full"
brew "id3v2"
brew "media-info"
brew "mkvtoolnix"
brew "mp3info"
brew "mp4v2"
brew "nicotine-plus"
brew "sox"
brew "yt-dlp"
if OS.mac?
  cask "fission"
  cask "handbrake-app"
  cask "kid3"
  cask "metaz", args: { appdir: "~/Applications" }
  cask "vlc"
  cask "xld"
end

### images

brew "exif"
brew "exiftool"
brew "zgracem/formulae/imagemagick-full-plus", link: true
brew "mozjpeg"
brew "pngquant"
brew "webp"

if OS.mac?
  brew "folderify"
  brew "imageoptim-cli"
  brew "imagesnap"
  cask "zgracem/formulae/acorn@preview"
  cask "imageoptim", args: { appdir: "/Applications" }
  cask "retrobatch"
end

### internet stuff

brew "aria2"
brew "curl"
brew "netcat"
brew "wget"

brew "alpine"
brew "bombadillo"
brew "links"
brew "lynx"
brew "newsboat"

if OS.mac?
  brew "dnsmasq", restart_service: :changed
  brew "tnftpd"
  brew "transmission-cli"
  cask "chatterino"
  cask "discord"
  cask "transmission"
  cask "transmit"
end

### security

brew "gnupg"

if OS.mac?
  brew "pinentry-mac"
  brew "ykman"
  cask "yubico-authenticator"
end

# ----------------------------------------------------------------------------
# development
# ----------------------------------------------------------------------------

brew "git"
brew "mercurial"
brew "subversion"

brew "powershell"

if OS.mac?
  brew "autoconf"
  brew "cmake"
  brew "glib"
  brew "llvm"
  brew "openjdk", postinstall: "sudo ln -sfn ${HOMEBREW_PREFIX}/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk"
  brew "texinfo"
end

# ruby
brew "rbenv"
brew "rbenv-bundler"
brew "rbenv-default-gems"
brew "ruby-build"
brew "taglib" # for `taglib-ruby` gem

# JavaScript
brew "node"
brew "coffeescript"
brew "typescript"
brew "yarn"

# Python
brew "pyenv"

# VS Code extensions
brew "shellcheck"
brew "shfmt"

# (Dart) Sass
brew "dart-sass"

# web fonts
brew "fontforge"
tap "bramstein/webfonttools", trusted: true
brew "bramstein/webfonttools/sfnt2woff-zopfli"
brew "bramstein/webfonttools/sfnt2woff"
brew "bramstein/webfonttools/woff2"

if OS.mac?
  # Flipper Zero
  brew "minicom"
  brew "ufbt"
  cask "qflipper"

  # virtual machines
  brew "icoutils" # Extract resources from Windows binaries
end

# ----------------------------------------------------------------------------
# fun & games
# ----------------------------------------------------------------------------

brew "cowsay-org/cowsay/cowsay", trusted: true
brew "dosbox-x"
brew "fastfetch"
brew "figlet"
brew "fortune"
brew "lolcat"
brew "zgracem/formulae/nethack@3.67"
brew "nethack"
brew "toilet"

if OS.mac?
  cask "inform"
  cask "steam", args: { appdir: "/Applications" }
  # cask "steamre/tools/depotdownloader", trusted: true
  cask "twine-app"
  cask "unity-hub"
end

# ----------------------------------------------------------------------------
# my stuff
# ----------------------------------------------------------------------------

brew "zgracem/formulae/calendar"
brew "zgracem/formulae/zgm-calendar-data"

# ----------------------------------------------------------------------------
# casks
# ----------------------------------------------------------------------------

if OS.mac?
  cask "alfred"
  cask "bettermouse"
  cask "fantastical"
  cask "firefox", args: { appdir: "/Applications" }
  cask "istat-menus", args: { appdir: "/Applications" }
  cask "iterm2"
  cask "little-snitch", args: { appdir: "/Applications" }
  cask "zgracem/formulae/lockscreen"
  cask "name-mangler"
  cask "obsidian"
  cask "sublime-merge"
  cask "superduper"
  cask "swiftbar"
  cask "visual-studio-code"
  cask "xscreensaver"

  cask "appcleaner"
  cask "disk-drill"
  cask "file-juicer"
  cask "grandperspective"
  cask "pdf-expert"
  cask "pearcleaner"
  cask "raspberry-pi-imager"
  cask "soulver-cli"
  cask "ungoogled-chromium"
  cask "vnc-viewer"
  cask "winclone"

  # QuickLook
  cask "qldds" # deprecated but still works
  cask "qlmarkdown"
  cask "suspicious-package" # .pkg files
  cask "syntax-highlight"
end

# ----------------------------------------------------------------------------
# Mac App Store
# ----------------------------------------------------------------------------

if OS.mac?
  brew "mas"

  # essentials
  mas "ColorSlurp", id: 1287239339
  mas "Divvy", id: 413857545
  mas "Mactracker", id: 430255202
  mas "Soulver 3", id: 1508732804
  mas "The Archive Browser", id: 510232205
  mas "Things", id: 904280696

  # more
  mas "1Blocker", id: 1365531024
  mas "MacFamilyTree 10", id: 1567970985
  mas "Sirds", id: 547093431
  mas "Steam Link", id: 1246969117
  mas "Vinegar", id: 1591303229
  mas "Wipr", id: 1320666476

  # Apple stuff
  mas "Apple Configurator", id: 1037126344
  mas "GarageBand", id: 682658836
  mas "iMovie", id: 408981434
  mas "Keynote", id: 409183694
  mas "Numbers", id: 409203825
  mas "Pages", id: 409201541
end

# ----------------------------------------------------------------------------
# flatpak
# ----------------------------------------------------------------------------

if OS.linux?
  flatpak "com.usebottles.bottles"
  flatpak "com.vscodium.codium"
  flatpak "org.kde.filelight"
  flatpak "org.gnome.FileRoller"
  flatpak "org.mozilla.firefox"
  flatpak "io.github.zyedidia.micro"
  flatpak "com.valvesoftware.SteamLink"
  flatpak "com.transmissionbt.Transmission"
  flatpak "org.videolan.VLC"
end
