complete -c vsdeploy -s p -d 'Only fix permissions'
complete -c vsdeploy -s i -d 'Only process new Stylebook images'
complete -c vsdeploy -s j -d 'Only rebuild JSON schema support files'
complete -c vsdeploy -o js -d 'Rebuild JSON & sync w/ server'
complete -c vsdeploy -s s -d 'Only sync source w/ server'
complete -c vsdeploy -s b -d 'Only trigger remote build'
complete -c vsdeploy -o sb -d 'Sync source & trigger remote build'
complete -c vsdeploy -s d -d 'Only rebuild docs locally'
complete -c vsdeploy -o ds -d 'Rebuild docs & sync'
complete -c vsdeploy -s l -d 'Only rebuild site locally'
complete -c vsdeploy -s S -d 'Only sync built site w/ server'
complete -c vsdeploy -o lS -d 'Rebuild site locally & sync'
