# unar <https://theunarchiver.com/command-line>

complete -c unar -s o -o output-directory -r -d 'Directory for writing archive contents'
complete -c unar -s f -o force-overwrite -d 'Always overwrite existing files'
complete -c unar -s r -o force-rename -d 'Always rename files when existing'
complete -c unar -s s -o force-skip -d 'Always skip existing files'
complete -c unar -s d -o force-directory -d 'Always create containing directory'
complete -c unar -s D -o no-directory -d 'Never create a containing directory'
complete -c unar -s p -o password -x -d 'Password for decrypting protected archives'
complete -c unar -s e -o encoding -x -d 'Encoding for filenames in the archive'
complete -c unar -s E -o password-encoding -x -d 'Encoding for the archive password'
complete -c unar -s i -o indexes -d 'Specify files to list by index'
complete -c unar -o nr -o no-recursion -d 'Do not list contents of nested archives'
complete -c unar -s t -o copy-time -d 'Copy modification time from archive'
complete -c unar -o nq -o no-quarantine -d 'Do not copy Finder quarantine metadata'
complete -c unar -s k -o forks -xa 'fork visible hidden skip' -d 'How to handle macOS resource forks'
complete -c unar -s q -o quiet -d 'Run quietly'
complete -c unar -s v -o version -d 'Print version'
complete -c unar -s h -o help -d 'Display help'
