export RUBYLIB="$HOME/lib/ruby"
export RI="--format=ansi"
export IRBRC="$XDG_CONFIG_HOME/ruby/irbrc"
export PRYRC="$XDG_CONFIG_HOME/ruby/pryrc"
export RUBOCOP_CACHE_ROOT="${XDG_CACHE_HOME:-$HOME/var/cache}"
