complete -c mansrc -x -a '(__fish_complete_man)'
complete -c mansrc -x -n 'not __fish_complete_man' -a 1 -d 'Program section'
complete -c mansrc -x -n 'not __fish_complete_man' -a 2 -d 'Syscall section'
complete -c mansrc -x -n 'not __fish_complete_man' -a 3 -d 'Library section'
complete -c mansrc -x -n 'not __fish_complete_man' -a 4 -d 'Device section'
complete -c mansrc -x -n 'not __fish_complete_man' -a 5 -d 'File format section'
complete -c mansrc -x -n 'not __fish_complete_man' -a 6 -d 'Games section'
complete -c mansrc -x -n 'not __fish_complete_man' -a 7 -d 'Misc section'
complete -c mansrc -x -n 'not __fish_complete_man' -a 8 -d 'Admin section'
complete -c mansrc -x -n 'not __fish_complete_man' -a 9 -d 'Kernel section'
complete -c mansrc -x -n 'not __fish_complete_man' -a tcl -d 'Tcl section'
complete -c mansrc -x -n 'not __fish_complete_man' -a n -d 'New section'
complete -c mansrc -x -n 'not __fish_complete_man' -a l -d 'Local section'
complete -c mansrc -x -n 'not __fish_complete_man' -a p
complete -c mansrc -x -n 'not __fish_complete_man' -a o -d 'Old section'
